{
 "title": "Transaction App - Worker",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Worker Method Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(transactionApp_worker_request_duration_seconds[5m])) by (method)"
    }
   ]
  },
  {
   "title": "Worker Ping Called",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(transactionApp_worker_ping_called[5m]) "
    }
   ]
  },
  {
   "title": "Worker Total Method Duration time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(transactionApp_worker_request_duration_seconds_sum) by (method)"
    }
   ]
  },
  {
   "title": "GetAllJobs Called",
   "type": "graph",
   "description": "All HTTP request that the UI service receives",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(transactionApp_worker_getjobs_called[5m]) "
    }
   ]
  },
  {
   "title": "Worker Method Call Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(transactionApp_worker_request_duration_seconds_count[5m])) by (method) "
    }
   ]
  },
  {
   "title": "count of New Job created",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(transactionApp_worker_newjobs_runned[5m])"
    }
   ]
  }
 ]
}