{
 "title": "Transaction App - API Server",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "API Server Method Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(transactionApp_apiserver_request_duration_seconds[5m])) by (method)"
    }
   ]
  },
  {
   "title": "New Jobs created",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(transactionApp_apiserver_new_jobs[1m])  "
    }
   ]
  },
  {
   "title": "API Server GetAllNodes Called",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(transactionApp_apiserver_getallnodes_called[5m])"
    }
   ]
  },
  {
   "title": "API Server Total Method Duration time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(transactionApp_apiserver_request_duration_seconds_sum) by (method)"
    }
   ]
  },
  {
   "title": "API Server Method Call Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(transactionApp_apiserver_request_duration_seconds_count[5m])) by (method) "
    }
   ]
  }
 ]
}