global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#devops'
