---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    app: transaction
    component: jaeger
spec:
  ports:
  - port: 16686
    name: port-16686
    protocol: TCP
    targetPort: 16686
  - port: 5775
    name: port-5775
    protocol: TCP
    targetPort: 5775
  selector:
    app: transaction
    component: jaeger
