// Code generated by protoc-gen-go. DO NOT EDIT.
// source: worker.proto

package pb_worker

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ff6184b07e587a, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type PingReply struct {
	Jobs                 int32    `protobuf:"varint,1,opt,name=jobs,proto3" json:"jobs,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReply) Reset()         { *m = PingReply{} }
func (m *PingReply) String() string { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()    {}
func (*PingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ff6184b07e587a, []int{1}
}

func (m *PingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReply.Unmarshal(m, b)
}
func (m *PingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReply.Marshal(b, m, deterministic)
}
func (m *PingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReply.Merge(m, src)
}
func (m *PingReply) XXX_Size() int {
	return xxx_messageInfo_PingReply.Size(m)
}
func (m *PingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReply.DiscardUnknown(m)
}

var xxx_messageInfo_PingReply proto.InternalMessageInfo

func (m *PingReply) GetJobs() int32 {
	if m != nil {
		return m.Jobs
	}
	return 0
}

func (m *PingReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type GetJobsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobsRequest) Reset()         { *m = GetJobsRequest{} }
func (m *GetJobsRequest) String() string { return proto.CompactTextString(m) }
func (*GetJobsRequest) ProtoMessage()    {}
func (*GetJobsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ff6184b07e587a, []int{2}
}

func (m *GetJobsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobsRequest.Unmarshal(m, b)
}
func (m *GetJobsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobsRequest.Marshal(b, m, deterministic)
}
func (m *GetJobsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobsRequest.Merge(m, src)
}
func (m *GetJobsRequest) XXX_Size() int {
	return xxx_messageInfo_GetJobsRequest.Size(m)
}
func (m *GetJobsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobsRequest proto.InternalMessageInfo

type Job struct {
	ID                   string               `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Per                  float32              `protobuf:"fixed32,2,opt,name=per,proto3" json:"per,omitempty"`
	Duration             float32              `protobuf:"fixed32,3,opt,name=duration,proto3" json:"duration,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=startTime,proto3" json:"startTime,omitempty"`
	FinishTime           *timestamp.Timestamp `protobuf:"bytes,5,opt,name=finishTime,proto3" json:"finishTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ff6184b07e587a, []int{3}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Job) GetPer() float32 {
	if m != nil {
		return m.Per
	}
	return 0
}

func (m *Job) GetDuration() float32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Job) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Job) GetFinishTime() *timestamp.Timestamp {
	if m != nil {
		return m.FinishTime
	}
	return nil
}

type GetJobsReply struct {
	Jobs                 []*Job   `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobsReply) Reset()         { *m = GetJobsReply{} }
func (m *GetJobsReply) String() string { return proto.CompactTextString(m) }
func (*GetJobsReply) ProtoMessage()    {}
func (*GetJobsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ff6184b07e587a, []int{4}
}

func (m *GetJobsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobsReply.Unmarshal(m, b)
}
func (m *GetJobsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobsReply.Marshal(b, m, deterministic)
}
func (m *GetJobsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobsReply.Merge(m, src)
}
func (m *GetJobsReply) XXX_Size() int {
	return xxx_messageInfo_GetJobsReply.Size(m)
}
func (m *GetJobsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobsReply proto.InternalMessageInfo

func (m *GetJobsReply) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func (m *GetJobsReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type NewJobRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewJobRequest) Reset()         { *m = NewJobRequest{} }
func (m *NewJobRequest) String() string { return proto.CompactTextString(m) }
func (*NewJobRequest) ProtoMessage()    {}
func (*NewJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ff6184b07e587a, []int{5}
}

func (m *NewJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewJobRequest.Unmarshal(m, b)
}
func (m *NewJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewJobRequest.Marshal(b, m, deterministic)
}
func (m *NewJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewJobRequest.Merge(m, src)
}
func (m *NewJobRequest) XXX_Size() int {
	return xxx_messageInfo_NewJobRequest.Size(m)
}
func (m *NewJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewJobRequest proto.InternalMessageInfo

type NewJobReply struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewJobReply) Reset()         { *m = NewJobReply{} }
func (m *NewJobReply) String() string { return proto.CompactTextString(m) }
func (*NewJobReply) ProtoMessage()    {}
func (*NewJobReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ff6184b07e587a, []int{6}
}

func (m *NewJobReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewJobReply.Unmarshal(m, b)
}
func (m *NewJobReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewJobReply.Marshal(b, m, deterministic)
}
func (m *NewJobReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewJobReply.Merge(m, src)
}
func (m *NewJobReply) XXX_Size() int {
	return xxx_messageInfo_NewJobReply.Size(m)
}
func (m *NewJobReply) XXX_DiscardUnknown() {
	xxx_messageInfo_NewJobReply.DiscardUnknown(m)
}

var xxx_messageInfo_NewJobReply proto.InternalMessageInfo

func (m *NewJobReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NewJobReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "pb.worker.PingRequest")
	proto.RegisterType((*PingReply)(nil), "pb.worker.PingReply")
	proto.RegisterType((*GetJobsRequest)(nil), "pb.worker.GetJobsRequest")
	proto.RegisterType((*Job)(nil), "pb.worker.Job")
	proto.RegisterType((*GetJobsReply)(nil), "pb.worker.GetJobsReply")
	proto.RegisterType((*NewJobRequest)(nil), "pb.worker.NewJobRequest")
	proto.RegisterType((*NewJobReply)(nil), "pb.worker.NewJobReply")
}

func init() { proto.RegisterFile("worker.proto", fileDescriptor_e4ff6184b07e587a) }

var fileDescriptor_e4ff6184b07e587a = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0xfd, 0xda, 0x02, 0x9f, 0x9d, 0x42, 0x25, 0x13, 0x83, 0xb5, 0x17, 0x49, 0x4f, 0x3d, 0x95,
	0x88, 0x89, 0x31, 0xc6, 0xc4, 0x0b, 0x89, 0x81, 0x83, 0x31, 0x0d, 0x89, 0x67, 0x36, 0x2c, 0xb8,
	0x0a, 0x6c, 0xdd, 0x2e, 0x21, 0xfc, 0x34, 0x4f, 0xfe, 0x35, 0xb3, 0xbb, 0xb4, 0x96, 0x80, 0xf1,
	0x36, 0x3b, 0xf3, 0xde, 0x9b, 0x7d, 0x6f, 0xa0, 0xb9, 0xe1, 0xe2, 0x9d, 0x8a, 0x24, 0x13, 0x5c,
	0x72, 0x74, 0x33, 0x92, 0x98, 0x46, 0x78, 0x39, 0xe7, 0x7c, 0xbe, 0xa0, 0x3d, 0x3d, 0x20, 0xeb,
	0x59, 0x4f, 0xb2, 0x25, 0xcd, 0xe5, 0x64, 0x99, 0x19, 0x6c, 0xd4, 0x02, 0xef, 0x99, 0xad, 0xe6,
	0x29, 0xfd, 0x58, 0xd3, 0x5c, 0x46, 0x57, 0xe0, 0x9a, 0x67, 0xb6, 0xd8, 0x22, 0x42, 0xed, 0x8d,
	0x93, 0x3c, 0xb0, 0xba, 0x56, 0x5c, 0x4f, 0x75, 0x8d, 0x6d, 0x70, 0xa8, 0x10, 0x81, 0xdd, 0xb5,
	0x62, 0x37, 0x55, 0x65, 0xd4, 0x06, 0xff, 0x91, 0xca, 0x11, 0x27, 0x79, 0x21, 0xf2, 0x69, 0x81,
	0x33, 0xe2, 0x04, 0x7d, 0xb0, 0x87, 0x03, 0xcd, 0x76, 0x53, 0x7b, 0x38, 0x50, 0xdc, 0x8c, 0x1a,
	0xae, 0x9d, 0xaa, 0x12, 0x43, 0x38, 0x99, 0xae, 0xc5, 0x44, 0x32, 0xbe, 0x0a, 0x1c, 0xdd, 0x2e,
	0xdf, 0x78, 0x0b, 0x6e, 0x2e, 0x27, 0x42, 0x8e, 0xd9, 0x92, 0x06, 0xb5, 0xae, 0x15, 0x7b, 0xfd,
	0x30, 0x31, 0x76, 0x92, 0xc2, 0x4e, 0x32, 0x2e, 0xec, 0xa4, 0x3f, 0x60, 0xbc, 0x03, 0x98, 0xb1,
	0x15, 0xcb, 0x5f, 0x35, 0xb5, 0xfe, 0x27, 0xb5, 0x82, 0x8e, 0x06, 0xd0, 0x2c, 0xdd, 0xa8, 0x0c,
	0xa2, 0x32, 0x03, 0x27, 0xf6, 0xfa, 0x7e, 0x52, 0x46, 0x9b, 0x8c, 0x38, 0xf9, 0x35, 0x93, 0x53,
	0x68, 0x3d, 0xd1, 0x8d, 0x42, 0xec, 0x22, 0xe9, 0x81, 0x57, 0x34, 0x94, 0xaa, 0x0f, 0x36, 0x9b,
	0x16, 0xc9, 0xb0, 0xe9, 0xa1, 0x42, 0xff, 0xcb, 0x82, 0xc6, 0x8b, 0x5e, 0x84, 0x37, 0x50, 0x53,
	0x37, 0xc1, 0x4e, 0x65, 0x79, 0xe5, 0x66, 0xe1, 0xd9, 0x41, 0x3f, 0x5b, 0x6c, 0xa3, 0x7f, 0xf8,
	0x00, 0xff, 0x77, 0x56, 0xf0, 0xa2, 0x02, 0xd9, 0x3f, 0x56, 0x78, 0x7e, 0x6c, 0x64, 0x04, 0xee,
	0xa1, 0x61, 0x3e, 0x8d, 0x41, 0x05, 0xb4, 0x67, 0x2c, 0xec, 0x1c, 0x99, 0x68, 0x36, 0x69, 0xe8,
	0xa4, 0xaf, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x2a, 0xe3, 0xe5, 0xdd, 0x9c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WorkerClient is the client API for Worker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkerClient interface {
	// PingPong interaction
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	GetJobs(ctx context.Context, in *GetJobsRequest, opts ...grpc.CallOption) (*GetJobsReply, error)
	NewJob(ctx context.Context, in *NewJobRequest, opts ...grpc.CallOption) (*NewJobReply, error)
}

type workerClient struct {
	cc *grpc.ClientConn
}

func NewWorkerClient(cc *grpc.ClientConn) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, "/pb.worker.Worker/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) GetJobs(ctx context.Context, in *GetJobsRequest, opts ...grpc.CallOption) (*GetJobsReply, error) {
	out := new(GetJobsReply)
	err := c.cc.Invoke(ctx, "/pb.worker.Worker/GetJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) NewJob(ctx context.Context, in *NewJobRequest, opts ...grpc.CallOption) (*NewJobReply, error) {
	out := new(NewJobReply)
	err := c.cc.Invoke(ctx, "/pb.worker.Worker/NewJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServer is the server API for Worker service.
type WorkerServer interface {
	// PingPong interaction
	Ping(context.Context, *PingRequest) (*PingReply, error)
	GetJobs(context.Context, *GetJobsRequest) (*GetJobsReply, error)
	NewJob(context.Context, *NewJobRequest) (*NewJobReply, error)
}

func RegisterWorkerServer(s *grpc.Server, srv WorkerServer) {
	s.RegisterService(&_Worker_serviceDesc, srv)
}

func _Worker_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.worker.Worker/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_GetJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).GetJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.worker.Worker/GetJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).GetJobs(ctx, req.(*GetJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_NewJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).NewJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.worker.Worker/NewJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).NewJob(ctx, req.(*NewJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Worker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.worker.Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Worker_Ping_Handler,
		},
		{
			MethodName: "GetJobs",
			Handler:    _Worker_GetJobs_Handler,
		},
		{
			MethodName: "NewJob",
			Handler:    _Worker_NewJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "worker.proto",
}
